### ISSUE TITLE
Swift Programming language 

### ISSUE THREAD

**Issue by MagedGDEV** [MagedGDEV/IOS_Dev_Learning#1]
# TO-DOs: Introduction To SWIFT
> 100 Days of SWIFTUI content

**Comment by MagedGDEV** [comment]
# variables, constants, strings, and numbers

- [x] [Introduction: Why Swift?](https://www.hackingwithswift.com/quick-start/beginners/why-swift)
- [x] [Introduction: About this course](https://www.hackingwithswift.com/quick-start/beginners/about-this-course)
- [x] [Introduction: How to follow along](https://www.hackingwithswift.com/quick-start/beginners/how-to-follow-along)
- [x] [How to create variables and constants](https://www.hackingwithswift.com/quick-start/beginners/how-to-create-variables-and-constants)
   - [ ] [Why does Swift have variables?](https://www.hackingwithswift.com/quick-start/understanding-swift/why-does-swift-have-variables)
   - [ ] [Why does Swift have constants as well as variables?](https://www.hackingwithswift.com/quick-start/understanding-swift/why-does-swift-have-constants-as-well-as-variables)
   - [ ] [Variables](https://www.hackingwithswift.com/review/variables)
   - [ ] [Constants](https://www.hackingwithswift.com/review/constants)
- [ ] [How to create strings](https://www.hackingwithswift.com/quick-start/beginners/how-to-create-strings)
   - [ ] [Why does Swift need multi-line strings?](https://www.hackingwithswift.com/quick-start/understanding-swift/why-does-swift-need-multi-line-strings)
   - [ ] [Multi-line strings](https://www.hackingwithswift.com/review/multi-line-strings)
- [ ] [How to store whole numbers](https://www.hackingwithswift.com/quick-start/beginners/how-to-store-whole-numbers)
   - [ ] [Strings and integers](https://www.hackingwithswift.com/review/strings-and-integers)
- [ ] [How to store decimal numbers](https://www.hackingwithswift.com/quick-start/beginners/how-to-store-decimal-numbers)
   - [ ] [Why does Swift need both Doubles and Integers?](https://www.hackingwithswift.com/quick-start/understanding-swift/why-does-swift-need-both-doubles-and-integers)
   - [ ] [Why is Swift a type-safe language?](https://www.hackingwithswift.com/quick-start/understanding-swift/why-is-swift-a-type-safe-language)
